sudo: required
services: 
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
# before_install:
#   - openssl aes-256-cbc -K $encrypted_e3870b75d381_key -iv $encrypted_e3870b75d381_iv -in multi-cluster-278002-1f481b18a15c.json.enc -out multi-cluster-278002-1f481b18a15c.json -d
#   - curl https://sdk.cloud.google.com | bash > /dev/null;
#   - source $HOME/google-cloud-sdk/path.bash.inc
#   - gcloud components update kubectl 
#   - gcloud auth activate-service-account --key-file= multi-cluster-278002-1f481b18a15c.json
#   - gcloud config set project project-id
#   - gcloud config set compute/zone compute-zone
#   - gcloud container clusters get-credentials cluster-name
#   - echo '$DOCKER_PASSWORD' | docker login -u '$DOCKER_USERNAME' --password-stdin